/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Carlos Gomez
 */
public class Make extends javax.swing.JFrame {

    /**
     * Creates new form Make
     */
    public static int estructura = Ventana.estructura;
    // 0 es cola
    // 1 es pila
    public static int horiginal=0;
    public static int voriginal=315;
    public static int rr=0;
    public static int tamfila=2;
    public static int tamcolumna=4;
    public static Raiz matriz = new Raiz();
    public static Raiz reinicio = new Raiz();
    private JPanel jPanel0;
    private JScrollPane scroll;
    private JPanel jPanel1;
    private JScrollPane scroll1;
    private JPanel jpanelver;
    private JPanel jpanelhor;
    private JScrollPane scrollh;
    private JScrollPane scrollv;
    public static listasdobles lista = Ventana.otra;
    public static listasdobles auxiliar = lista;
    public Make() {
        
        //new GridBagLayout()
        jPanel0 = new JPanel();
        jPanel0.setBounds(20,175,1020,430);
        add(jPanel0);
        scroll = new JScrollPane(jPanel0);
      //scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scroll.setBounds(20,175,1020,430);
        add(scroll);
        
        jPanel1 = new JPanel();
        jPanel1.setBounds(20,40,1020,90);
        add(jPanel1);
        scroll1 = new JScrollPane(jPanel1);
      //scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scroll1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scroll1.setBounds(20,40,1020,90);
        add(scroll1);
    
        System.out.println("-------PILA O COLA-----\n 0. cola \n 1. pila");
        System.out.println(estructura); 
        JOptionPane.showMessageDialog(rootPane,"-------PILA O COLA-----\n 0. cola \n 1. pila");
        
            
        initComponents();
        
        lista.imprimirlista();
        listasdobles auxiliar = lista;
        rr = lista.tamaño();
        System.out.println("esta es la r tamaño"+lista.tamaño());
        
        for(int i=1;i<rr;i++){
        String path="";
        String name="";
            if(estructura==0){
                path = auxiliar.buscarPathInverso(i);
                name = auxiliar.buscarNombreInverso(i);
            }         
            if(estructura==1){
                path = auxiliar.buscarPath(i);
                name = auxiliar.buscarNombre(i);
            }
        Portada nueva = new Portada();
        nueva.crearImagen(jPanel1,path,name);  
        }   
    
 
           
        
        jPanel1.updateUI();
        jPanel0.updateUI();
        for(int x=0; x<tamcolumna;x++){
            int posx=x*50+40;
            int posy=0;
            Portada nuevo = new Portada();
            String nombrex="c"+x;
            nuevo.crearLabel(jPanel0, nombrex, posx, posy,matriz);
        }
        
        
        for(int y=0; y<tamfila;y++){
            int posx=0;
            int posy=340-y*50;
            Portada nuevo = new Portada();
            String nombrey="f"+y;
            nuevo.crearLabel(jPanel0, nombrey, posx, posy,matriz);
        }
    
        

        matriz.insertarFila(-1);
        matriz.insertarColumna(-1);
        System.out.println("MATRIZ ORTOGONAL--------");
        for(int x = 0; x<tamcolumna;x++){
            for(int y=0; y<tamfila;y++){
                matriz.insertar(matriz, 0, x, y);
            }
        }
        
        for(int x = 0; x<tamcolumna; x++){
            for(int y = 0;y<tamfila; y++){
                Portada nuevo = new Portada();
                int posx= x*50+20;
                int posy= 340-y*50;
              //  System.out.println("set Bounds: "+posx+","+posy);
                nuevo.crearMatriz(jPanel1,jPanel0,"cielo.png", posx, posy,x,y,lista,estructura,matriz);
            }
        }
    
        jPanel0.updateUI();
        System.out.println("    ESTURCTURA "+estructura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("xD:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 111, 29));

        jLabel3.setText("PERSONAJES:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        jLabel4.setText("TABLERO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, -1, -1));

        jLabel5.setText("X:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, 110, -1));

        jLabel6.setText("Y:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 120, 110, -1));

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 150, -1, -1));

        jButton2.setText("RESUMEN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 220, -1, -1));

        jButton3.setText("ADD COLUMNA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, 110, -1));

        jButton4.setText("ADD FILA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 350, 110, -1));

        jLabel9.setText("COLUMNA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 80, -1));

        jLabel10.setText("FILA:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 520, 50, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 450, 120, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 120, -1));

        jButton5.setText("ELIMINAR X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 480, 120, -1));

        jButton6.setText("ELIMINAR Y");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 580, 120, -1));

        jButton7.setText("PLAY!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world mario.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 620));

        jMenu1.setText("GRAFICAR");

        jMenuItem1.setText("GRAFICAR ORTOGONAL");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("GRAFICAR LISTA");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

                
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tamcolumna = tamcolumna+1;
        int columna=tamcolumna-1;
        System.out.println("TAMAÑO COLUMNA "+tamcolumna);
        for(int i=0;i<tamfila;i++){
            matriz.insertar(matriz, 0, columna, i);
        }
        int auxposx=0;
        int auxposy=0;
     //CREACION DE LA MATRIZ DE BOTONES
         for(int x = 0; x<tamcolumna; x++){
            for(int y = 0;y<tamfila;y++){
                 auxposx= x*50+20;
                 auxposy= 340-y*50;
             
            }
        }
         for(int  y =0;y<tamfila;y++){
             Portada nuevo = new Portada();
             int posy = 340-y*50;
             nuevo.crearMatriz(jPanel1, jPanel0, "cielo.png",auxposx, posy, columna, y, lista, estructura, matriz);
             System.out.println("   setBounds y "+posy);
         }
        System.out.println("    setBounds x "+auxposx);
        for(int x=0; x<tamcolumna;x++){
            int posx=x*50+40;
            int posy=0;
            Portada nuevo = new Portada();
            String nombrex = "c"+x;
            nuevo.crearLabel(jPanel0, nombrex, posx, posy,matriz);
        }
        
        
        for(int y=0; y<tamfila;y++){
            int posx=0;
            int posy=340-y*50;
            Portada nuevo = new Portada();
            String nombrey = "f"+y;
            nuevo.crearLabel(jPanel0, nombrey, posx, posy,matriz);
        }
        jPanel0.repaint();
        jPanel0.updateUI();
        
     
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
        int auxX;
        String posx= jTextField1.getText();
        auxX = Integer.parseInt(posx);
        
        int auxY;
        String posy= jTextField2.getText();
        auxY = Integer.parseInt(posy);
        
        if(estructura==0){
            int cola = lista.buscaridCola();
            Personaje nodoaux = lista.DarObjetoCola();
            nodoaux.setX(auxX);
            nodoaux.setY(auxY);
            auxiliar.alta(nodoaux);
            System.out.println("ESTA ES LA COLA CON POS X Y");
            auxiliar.imprimirlista();
            lista.delete(cola);
        }
        if(estructura==1){
            int pila = lista.buscaridPila();
            Personaje nodoaux = lista.DarObjetoPila();
            nodoaux.setX(auxX);
            nodoaux.setY(auxY);
            auxiliar.alta(nodoaux);
            System.out.println("ESTA ES LA PILA CON POS X Y");
            auxiliar.imprimirlista();
            lista.delete(pila);
        }
      
    }
    catch(Exception ex){
    
    }    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int personaje = lista.contarObjetos("personaje");
        int hongo = lista.contarObjetos("hongo");
        int ficha = lista.contarObjetos("ficha");
        int monstruo = lista.contarObjetos("monstruo");
        int pared = lista.contarObjetos("pared");
        int suelo = lista.contarObjetos("suelo");
        int tortuga = lista.contarObjetos("tortuga");
        int castillo = lista.contarObjetos("castillo");
        JOptionPane.showMessageDialog(this,"RESUMEN: \n"
                + "\n Personaje: "+personaje
                + "\n Hongos: "+hongo
                + "\n Fichas: "+ficha
                + "\n Goombas: "+monstruo 
                + "\n Paredes: "+pared
                + "\n Suelos: "+suelo
                + "\n Tortugas: "+tortuga
                + "\n Castillos: "+castillo);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     matriz.columna.graphMatriz(matriz.fila.ultimo, matriz.columna.ultimo);   
       Funcion fun = new Funcion();
       fun.generar("Matriz Ortogonal Tablero");
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tamfila = tamfila +1;
        int fila = tamfila-1;
        System.out.println("TAMAÑO FILA "+tamfila);
 
        for(int i=0;i<tamcolumna;i++){
            matriz.insertar(matriz, 0, i,fila);
        }
        int auxposx=0;
        int auxposy=0;
     //CREACION DE LA MATRIZ DE BOTONES
         for(int x = 0; x<tamcolumna; x++){
            for(int y = 0;y<tamfila;y++){
                 auxposx= x*50+20;
                 auxposy= 340-y*50;
             
            }
        }

         for(int  x =0;x<tamcolumna;x++){
             Portada nuevo = new Portada();
             int posx = x*50+20;
             nuevo.crearMatriz(jPanel1, jPanel0, "cielo.png",posx, auxposy, x, fila, lista, estructura, matriz);
             System.out.println("   setBounds x "+posx);
         }
        
         System.out.println("    setBounds y "+auxposy);
        for(int x=0; x<tamcolumna;x++){
            int posx=x*50+40;
            int posy=0;
            Portada nuevo = new Portada();
            String nombrex="c"+x;
            nuevo.crearLabel(jPanel0, nombrex, posx, posy,matriz);
        }
        
        
        for(int y=0; y<tamfila;y++){
            int posx=0;
            int posy=340-y*50;
            Portada nuevo = new Portada();
            String nombrey="f"+y;
            nuevo.crearLabel(jPanel0, nombrey, posx, posy,matriz);
        }
        jPanel0.repaint();
        jPanel0.updateUI();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.out.println("hice clic ");
        Play p = new Play();
        p.matriz=matriz;
        p.tamfila=this.tamfila;
        p.tamcolumna=this.tamcolumna;
        reinicio = matriz;
        p.reini = this.reinicio;
        System.out.println("el q mando tamfila "+this.tamfila);
        System.out.println("el q mando tamcolumna "+this.tamcolumna);
        this.setVisible(false);
        p.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   
    try{    
       
           String nombrexx=jTextField3.getText();
           int nombrex = Integer.parseInt(nombrexx);
           if(nombrex!=0){
        for(int i=0;i<tamfila;i++){
            String name = nombrexx+","+i;
            Portada p = new Portada();
            p.eliminarT(jPanel0,name);
            
        }
        matriz.eliminarC(matriz.columna.ultimo,nombrex);
        tamcolumna=tamcolumna-1;}
            else{
            JOptionPane.showMessageDialog(this,"COLUMNA NO VALIDA SELECCIONE OTRA XD");
            }
    }
    catch(Exception ex){
    
    }
    
   
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   
   
    try{    
       
        String nombreyy=jTextField4.getText();
        int nombrey = Integer.parseInt(nombreyy);
        if(nombrey!=0){
        for(int i=0;i<tamcolumna;i++){
            String name = i+","+nombreyy;
            Portada p = new Portada();
            p.eliminarT(jPanel0,name);
            
        }
        matriz.eliminarF(matriz.fila.ultimo,nombrey);
        tamfila=tamfila-1;}
         else{
        JOptionPane.showMessageDialog(this,"FILA NO VALIDA SELECCIONE OTRA XD");
        }
    }
    catch(Exception ex){
    
    }
    
   
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyChar()=='d'){
       System.out.println("presionaste D xD");
       
       
   }
        
// TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Funcion f = new Funcion();
        f.generarListaDoble(lista);
        f.generar("LISTA DOBLE PERSONAJES TABLERO");

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Make().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
