/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Carlos Gomez
 */

public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public static listasdobles lista = new listasdobles();
    public static listasdobles aux = lista;
    public static listasdobles otra = new listasdobles();
    int id=1;
    public static int r=0;
    private JPanel jPanel0;
    int mario=0;
    int castillo=0;
    private JScrollPane scroll;
    int contar=0;
    public Ventana() {
        jPanel0 = new JPanel();
        jPanel0.setBounds(70,300,530,130);
        add(jPanel0);
        scroll = new JScrollPane(jPanel0);
      //scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setBounds(70,300,530,130);
        add(scroll);
        

        
        /*
        scroll = new JScrollPane(jPanel1);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scroll.setBounds(580,60,260,350);
        add(scroll);
        */
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mario.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hongo.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 100));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 110, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monstruo.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 100, 100));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pared.JPG"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 100));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suelo.JPG"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 110, 100));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tortuga.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, 100));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/castillo.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 100));

        jButton10.setText("PILA :D ->");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 110, -1));

        jButton1.setText("COLA :) ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 110, -1));

        jButton11.setText("MOSTRAR LISTA");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 140, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 30, 40));

        jLabel2.setText("MI PERSONAJE :D ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, -1));

        jLabel3.setText("Eliminar Personaje :D");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 110, -1));

        jButton12.setText("Eliminar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 140, -1));

        jMenu1.setText("Graficar");

        jMenuItem1.setText("Graficar Lista Doble");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jugar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Make m = new Make();
        m.estructura = 1;
        
        this.setVisible(false);
        m.setVisible(true);
        m.jLabel1.setText("PILA (LIFO)");
        m.lista = otra;
        m.rr = r;
// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"mario.png",1,"personaje");
    lista.alta(b);
    otra.alta(b);
    mario = id;
    id = id+1;
    jButton2.setEnabled(false);
    jTextField1.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"hongo.png",1,"hongo");
    lista.alta(b);
    otra.alta(b);
    id = id+1;
    jTextField1.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"ficha.png",1,"ficha");
    lista.alta(b);
    otra.alta(b);
    id = id+1;      
    jTextField1.setText("");    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"monstruo.png",1,"monstruo");
    lista.alta(b);
    otra.alta(b);
    id = id+1;  
    jTextField1.setText("");    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"pared.JPG",0,"pared");
    lista.alta(b);
    otra.alta(b);
    id = id+1;  
    jTextField1.setText("");    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"suelo.JPG",0,"piso");
    lista.alta(b);
    otra.alta(b);
    id = id+1;  
    jTextField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"tortuga.png",1,"tortuga");
    lista.alta(b);
    otra.alta(b);
    id = id+1;          
    jTextField1.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    String nombre=jTextField1.getText();
    Personaje b = new Personaje(id,nombre,"castillo.png",0,"castillo");
    lista.alta(b);
    otra.alta(b);
    castillo = id;
    id = id+1;  
    jTextField1.setText("");
    jButton9.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jPanel0.removeAll(); 
        jPanel0.repaint(); 
        try{
        
        int auxid = 0;
        otra.delete(auxid);
        otra.imprimirlista();
        listasdobles auxiliar = otra;
        r = otra.tamaño();
        for(int i=1;i<r;i++){
        String nombre = auxiliar.buscarNombreInverso(i);
        String path = auxiliar.buscarPathInverso(i);
        int numeroid = auxiliar.buscaridInverso(i);
        Portada nueva = new Portada();
        nueva.crear(jPanel0,nombre,path,numeroid);  
        }   
        }catch(Exception ex){
        
        }
        
    jPanel0.updateUI();
    /*jPanel0.removeAll();
    listasdobles auxiliar = lista;
    System.out.println("id: "+id);
    r = id;
    for(int i=1;i<id;i++){
        String nombre = auxiliar.buscarNombre(i);
        String path = auxiliar.buscarPath(i);
        int numeroid = auxiliar.buscarid(i);
        Portada nueva = new Portada();
        nueva.crear(jPanel0,nombre,path,numeroid);  
        
    }
       
       jPanel0.repaint();
       Funcion f = new Funcion();
       f.generarListaDoble(auxiliar);
       f.generar("lista doble xd");
       auxiliar.imprimirlista();
       jPanel0.updateUI();*/
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jPanel0.removeAll(); 
        jPanel0.repaint(); 
        try{
        String sid = jTextField2.getText();
        
        int auxid = Integer.parseInt(sid);
        System.out.println("mario xd :"+mario);
        System.out.println("castillo xd: "+castillo);
        if(auxid==mario){
            jButton2.setEnabled(true);
        }
        if(auxid==castillo){
            jButton9.setEnabled(true);
        }
        otra.delete(auxid);
        otra.imprimirlista();
        listasdobles auxiliar = otra;
        r = otra.tamaño();
        for(int i=1;i<r;i++){
        String nombre = auxiliar.buscarNombreInverso(i);
        String path = auxiliar.buscarPathInverso(i);
        int numeroid = auxiliar.buscaridInverso(i);
        Portada nueva = new Portada();
        nueva.crear(jPanel0,nombre,path,numeroid);  
        }   
        }catch(Exception ex){
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Make m = new Make();
        m.estructura=0;
        this.setVisible(false);
        m.setVisible(true);
        m.jLabel1.setText("COLA (FIFO)");
        m.rr = otra.tamaño();
        m.lista = otra;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
